services:
  nginx:
    build:
      context: .
      dockerfile: ./app/nginx/Dockerfile
      args:
        NGINX_CONF: app/nginx/prod.conf
    restart: unless-stopped

  # No ports are exposed so we can use a private instance to check for broken
  # links. All scripts are executed within a container.
  nginx-test:
    build:
      context: .
      dockerfile: ./app/nginx/Dockerfile

  nginx-dev:
    build:
      context: .
      dockerfile: ./app/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html
    restart: unless-stopped

  sync:
    build: app/s3
    entrypoint: ["/app/bin/sync"]
    volumes:
      - ./s3:/s3

  seed:
    build: app/s3
    entrypoint: ["/app/bin/seed"]
    volumes:
      - ./s3:/s3

  webp:
    image: press-webp
    entrypoint: ["/app/bin/service"]
    volumes:
      - ./app/webp/input:/app/input
      - ./app/webp/output:/app/output
      - ../log:/app/log

  mermaid:
    image: minlag/mermaid-cli
    container_name: press-mermaid
    volumes:
      - ./:/data

  # Default port is 6379. Not exposed to the host to avoid port conflicts.
  # You can run redis-cli within this container.
  #   docker compose exec dragonfly redis-cli
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly

  shell:
    image: press-release
    working_dir: /data
    entrypoint: ["bash"]
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      REDIS_HOST: dragonfly
      REDIS_PORT: 6379
      TEST_HOST_URL: ${TEST_HOST_URL:-http://nginx-test}
      BASE_URL: ${BASE_URL:-https://anatomybook.art}
    volumes:
      - ./:/data
      - ./app/references:/app/references
